name: kotatogram-desktop
adopt-info: kotatogram
icon: Telegram/Resources/art/icon512@2x.png

base: core18
grade: stable
confinement: strict

architectures:
  - build-on: amd64
  - build-on: i386
  - build-on: arm64
  - build-on: armhf
  - build-on: ppc64el

apps:
  kotatogram-desktop:
    command: bin/desktop-launch kotatogram-desktop
    common-id: io.github.kotatogram
    desktop: share/applications/kotatogramdesktop.desktop
    environment:
      # Use GTK3 cursor theme, icon theme and open/save file dialogs.
      QT_QPA_PLATFORMTHEME: gtk3
      # The blocker is https://github.com/ubuntu/snapcraft-desktop-helpers/issues/172
      DISABLE_WAYLAND: 1
    plugs:
      - alsa
      - audio-playback
      - audio-record
      - desktop
      - desktop-legacy
      - home
      - network
      - network-manager
      - pulseaudio
      - removable-media
      - unity7
      - x11

plugs:
  # Support for common GTK themes
  # https://forum.snapcraft.io/t/how-to-use-the-system-gtk-theme-via-the-gtk-common-themes-snap/6235
  gsettings:
  gtk-3-themes:
    interface: content
    target: $SNAP/data-dir/themes
    default-provider: gtk-common-themes
  icon-themes:
    interface: content
    target: $SNAP/data-dir/icons
    default-provider: gtk-common-themes
  sound-themes:
    interface: content
    target: $SNAP/data-dir/sounds
    default-provider: gtk-common-themes

layout:
  /usr/share/alsa:
    bind: $SNAP/usr/share/alsa

parts:
  kotatogram:
    plugin: cmake
    source: .
    source-type: git
    parse-info: [share/metainfo/kotatogramdesktop.appdata.xml]
    build-packages:
      - gcc-8
      - g++-8
      - qtbase5-private-dev
      - libmapbox-variant-dev
      - libasound2-dev
      - libdbusmenu-qt5-dev
      - libhunspell-dev
      - liblz4-dev
      - liblzma-dev
      - libminizip-dev
      - libopus-dev
      - libpulse-dev
      - libssl-dev
      - zlib1g-dev
    stage-packages:
      - qt5-image-formats-plugins
      - libasound2
      - libdbusmenu-qt5-2
      - libhunspell-1.6-0
      - liblz4-1
      - liblzma5
      - libminizip1
      - libopus0
      - libpulse0
      - libssl1.1
      - zlib1g
    configflags:
      - -DCMAKE_C_COMPILER=gcc-8
      - -DCMAKE_CXX_COMPILER=g++-8
      - -DCMAKE_BUILD_TYPE=Release
      - -DTDESKTOP_API_ID=611335
      - -DTDESKTOP_API_HASH=d524b414d21f4d37f08684c1df41ac9c
      - -DDESKTOP_APP_USE_PACKAGED_FONTS=OFF
      - -DDESKTOP_APP_USE_PACKAGED_GSL=OFF
      - -DDESKTOP_APP_USE_PACKAGED_EXPECTED=OFF
      - -DDESKTOP_APP_USE_PACKAGED_RLOTTIE=OFF
      - -DTDESKTOP_USE_PACKAGED_TGVOIP=OFF
    override-pull: |
      snapcraftctl pull

      version="$(git describe --tags | sed -r 's,^k([0-9]\.[0-9]),\1,')"
      snapcraftctl set-version "$version"

      sed -i 's|^Icon=.*|Icon=/share/icons/hicolor/512x512/apps/kotatogram.png|g' lib/xdg/kotatogramdesktop.desktop
    override-build: |
      snapcraftctl build
      mkdir -p "$SNAPCRAFT_PART_INSTALL/etc/fonts"
      cp "$SNAPCRAFT_PART_SRC/Telegram/lib_ui/qt_conf/fc-custom.conf" "$SNAPCRAFT_PART_INSTALL/etc/fonts/fonts.conf"
    after:
      - cmake
      - desktop-qt5
      - ffmpeg
      - openal
      - range-v3
      - xxhash

  patches:
    plugin: dump
    source: Telegram/Patches
    prime: [-./*]

  desktop-qt5:
    source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
    source-subdir: qt
    plugin: make
    make-parameters: ["FLAVOR=qt5"]
    build-packages:
      - build-essential
      - qtbase5-dev
      - dpkg-dev
    stage-packages:
      - libxkbcommon0
      - ttf-ubuntu-font-family
      - dmz-cursor-theme
      - light-themes
      - adwaita-icon-theme
      - gnome-themes-standard
      - shared-mime-info
      - libqt5gui5
      - libgdk-pixbuf2.0-0
      - libqt5svg5 # for loading icon themes which are svg
      - try: [appmenu-qt5] # not available on core18
      - locales-all
      - xdg-user-dirs
      - fcitx-frontend-qt5
    stage: [-etc/fonts/fonts.conf]

  qt5-gtk-platform:
    plugin: nil
    stage-packages:
      - qt5-gtk-platformtheme
    stage: [-etc/fonts/fonts.conf]

  cmake:
    source: "https://gitlab.kitware.com/cmake/cmake.git"
    source-depth: 1
    source-tag: v3.16.4
    source-type: git
    plugin: make
    override-build: |
      ${SNAPCRAFT_PART_SRC}/bootstrap \
        --parallel=${SNAPCRAFT_PARALLEL_BUILD_COUNT} \
        -- \
        -DCMAKE_BUILD_TYPE=Release \
        -DCMAKE_INSTALL_PREFIX=/ \
        -DBUILD_TESTING=OFF
      snapcraftctl build
    build-packages:
      - build-essential
      - libssl-dev
      - libncurses5-dev
    stage-packages:
      - libssl1.1
      - libncurses5
      - libtinfo5
    prime: [-./*]

  ffmpeg:
    source: https://github.com/FFmpeg/FFmpeg.git
    source-depth: 1
    source-branch: release/4.2
    plugin: autotools
    build-packages:
      - yasm
      - libasound2-dev
      - libopus-dev
      - libva-dev
      - libvdpau-dev
    stage-packages:
      - libasound2
      - libopus0
      - libva2
      - libva-drm2
      - libvdpau1
    configflags:
      - --prefix=/usr
      - --disable-debug
      - --disable-programs
      - --disable-doc
      - --disable-autodetect
      - --disable-everything
      - --disable-neon
      - --disable-iconv
      - --enable-gpl
      - --enable-version3
      - --enable-libopus
      - --enable-vaapi
      - --enable-vdpau
      - --enable-decoder=aac
      - --enable-decoder=aac_latm
      - --enable-decoder=aasc
      - --enable-decoder=flac
      - --enable-decoder=gif
      - --enable-decoder=h264
      - --enable-decoder=mp1
      - --enable-decoder=mp1float
      - --enable-decoder=mp2
      - --enable-decoder=mp2float
      - --enable-decoder=mp3
      - --enable-decoder=mp3adu
      - --enable-decoder=mp3adufloat
      - --enable-decoder=mp3float
      - --enable-decoder=mp3on4
      - --enable-decoder=mp3on4float
      - --enable-decoder=mpeg4
      - --enable-decoder=msmpeg4v2
      - --enable-decoder=msmpeg4v3
      - --enable-decoder=opus
      - --enable-decoder=vorbis
      - --enable-decoder=wavpack
      - --enable-decoder=wmalossless
      - --enable-decoder=wmapro
      - --enable-decoder=wmav1
      - --enable-decoder=wmav2
      - --enable-decoder=wmavoice
      - --enable-encoder=libopus
      - --enable-hwaccel=h264_vaapi
      - --enable-hwaccel=h264_vdpau
      - --enable-hwaccel=mpeg4_vaapi
      - --enable-hwaccel=mpeg4_vdpau
      - --enable-parser=aac
      - --enable-parser=aac_latm
      - --enable-parser=flac
      - --enable-parser=h264
      - --enable-parser=mpeg4video
      - --enable-parser=mpegaudio
      - --enable-parser=opus
      - --enable-parser=vorbis
      - --enable-demuxer=aac
      - --enable-demuxer=flac
      - --enable-demuxer=gif
      - --enable-demuxer=h264
      - --enable-demuxer=mov
      - --enable-demuxer=mp3
      - --enable-demuxer=ogg
      - --enable-demuxer=wav
      - --enable-muxer=ogg
      - --enable-muxer=opus
    override-pull: |
      snapcraftctl pull
      patch -p1 < "$SNAPCRAFT_STAGE/ffmpeg.diff"
    after:
      - patches

  openal:
    source: https://github.com/kcat/openal-soft.git
    source-depth: 1
    source-tag: openal-soft-1.20.1
    plugin: cmake
    build-packages:
      - libasound2-dev
      - libpulse-dev
      - libsndio-dev
      - portaudio19-dev
    stage-packages:
      - libasound2
      - libpulse0
      - libportaudio2
      - libsndio6.1
    configflags:
      - -DCMAKE_BUILD_TYPE=Release
      - -DALSOFT_EXAMPLES=OFF
      - -DALSOFT_TESTS=OFF
      - -DALSOFT_UTILS=OFF
      - -DALSOFT_CONFIG=OFF

  range-v3:
    source: https://github.com/ericniebler/range-v3.git
    source-depth: 1
    source-tag: 0.10.0
    plugin: cmake
    configflags:
      - -DRANGE_V3_TESTS=OFF
      - -DRANGE_V3_EXAMPLES=OFF
      - -DRANGE_V3_DOCS=OFF
    prime: [-./*]

  xxhash:
    source: https://github.com/Cyan4973/xxHash.git
    source-depth: 1
    source-tag: v0.7.2
    plugin: make
    make-parameters: [PREFIX=]
    prime: [-./bin/*]
